Docker login
iron-io/functions pull request #547
Opened 2017-02-28 11:22 UTC by BupycHuk

closes #506

2017-02-28 11:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iron-io/functions?pullRequest=547) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iron-io/functions?pullRequest=547) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iron-io/functions?pullRequest=547) it.</sub>

2017-02-28 21:48 UTC, treeder requested changes
I wonder about the security implications of this. It may be that this features requires an authentication module or something?

2017-02-28 21:48 UTC, treeder commented on fn/login.go
> +	fmt.Println(`Added docker repo credentials`)
Why backticks?

2017-03-01 12:02 UTC, BupycHuk commented
@treeder 
I'm going to encrypt docker credentials using AES or RSA.
Do you think this is enough?

2017-03-07 16:01 UTC, treeder commented on api/server/server.go
> +		Key:       []byte("AES256Key-32Characters1234567890"),
User should pass this in through env var perhaps?

2017-03-07 17:01 UTC, treeder commented
Maybe we start here with global docker credentials, then once we add some authentication middleware, those could also have per user credentials.

2017-03-07 17:03 UTC, treeder commented
@BupycHuk has some conflicts here.

2017-03-15 11:49 UTC, BupycHuk commented
@treeder i have fixed conflicts and add new tests, could you take a look, pls

2019-02-15 11:54 UTC, closed without merging