#451 Added chocolatey package support for Functions.
iron-io/functions pull request #564
Opened 2017-03-02 11:28 UTC by martinpinto

Added a new package for chocolatey for the latest Functions version.

2017-03-10 17:48 UTC, denismakogon commented on fn/chocolatey/functions.nuspec
> +    <tags>serverless faas docker lambda</tags>
IFAIK we'd like to keep ourselves for being associated with Serverless (see https://serverless.com/). So it'll be better to have next tags:
`functions faas docker containers` (as an alternative - include COE there).

2017-03-10 17:48 UTC, denismakogon commented on fn/chocolatey/functions.nuspec
> +    <projectUrl>https://github.com/iron-io/functions/</projectUrl>
trailing slash? just remove slash right after `functions`

2017-03-10 19:13 UTC, treeder commented on fn/chocolatey/functions.nuspec
> +    <tags>serverless faas docker lambda</tags>
I'd say keep serverless and add functions. We do want to be associated with the term serverless as that's what everyone is referring to it as for the time being.

2017-03-10 20:11 UTC, treeder commented on fn/chocolatey/tools/chocolateyinstall.ps1
> +$url        = 'https://github.com/iron-io/functions/releases/download/0.2.25/fn.exe'
Could this URL always grab the latest release?  Similar to `install.sh` ?

2017-03-12 12:34 UTC, martinpinto commented on fn/chocolatey/functions.nuspec
> +    <projectUrl>https://github.com/iron-io/functions/</projectUrl>
ok done. Removed both the trailing slash from the `<projectUrl>` and `<packageSourceUrl>`.

2017-03-12 12:36 UTC, martinpinto commented on fn/chocolatey/functions.nuspec
> +    <tags>serverless faas docker lambda</tags>
ok done. Kept `serverless` and added `functions`.

2017-03-12 12:44 UTC, martinpinto commented on fn/chocolatey/tools/chocolateyinstall.ps1
> +$url        = 'https://github.com/iron-io/functions/releases/download/0.2.25/fn.exe'
Unfortunately this URL is bound to that version. We might need to adjust scripts to auto increase the version. Updated version to 0.2.36.

2017-03-24 04:52 UTC, denismakogon approved these changes

2017-03-24 17:09 UTC, treeder requested changes

2017-03-24 17:09 UTC, treeder commented on fn/chocolatey/tools/chocolateyinstall.ps1
> +$url        = 'https://github.com/iron-io/functions/releases/download/0.2.25/fn.exe'
Yes, we need to make the scripts update the version on release, same way as we do for git, docker, cli install, etc. 

How does this get submitted to Chocolatey?  We'll want to make sure that's automated too.

2017-03-29 19:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iron-io/functions?pullRequest=564) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/iron-io/functions?pullRequest=564) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: seiflotfy<br/>:white_check_mark: martinpinto<br/>:white_check_mark: treeder<br/>:white_check_mark: pedronasser<br/>:white_check_mark: denismakogon<br/>:x: CircleCI<br/><hr/>**CircleCI** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iron-io/functions?pullRequest=564) it.</sub>

2026-03-25 00:34 UTC, closed without merging